### ISSUE TITLE
[Server] 테스트 서버환경 구축

### ISSUE THREAD

**Issue by doldolma** [codestates/Gunsigi#11]
### ISSUE
- Group:  `server`
- Type: `deploy`
- Detail: 테스트 서버 환경 구축

### TODO
1. [ ] 테스트 서버 환경설정
2. [ ] 테스트 DB 환경설정
3. [ ] 자동배포 환경 구축

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint 2`
