### ISSUE TITLE
[Client] 랜딩 페이지 목업 구현 part.3

### ISSUE THREAD

**Issue by sarahsea** [codestates/Gunsigi#16]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 목업 구현

### TODO
1. [ ] 랜딩 탑버튼, 푸터, 네브, 네브체인지
2. [ ] 랜딩 모바일 ->태블릿 ->  데스크탑 반응형 설정
3. [ ] 랜딩 킥기능 설명 페이지 추가

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
