### ISSUE TITLE
[Client] 회원가입 후 이메일 인증 기능

### ISSUE THREAD

**Issue by junghoonme** [codestates/Gunsigi#179]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 회원 가입 후 이메일 인증 기능 구현

### TODO
1. [x] 이메일 전송 알림 모달
2. [x] 전송 이메일 양식 구현
3. [x] 이메일 인증 유저 표시

### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__4__`
