### ISSUE TITLE
[Client] 검색페이지 이슈 정의하기

### ISSUE THREAD

**Issue by seola25** [codestates/Gunsigi#217]
### ISSUE
- Group:  `client`
- Type: `update`
- Detail: 전체 코드 다시보고, 문제로 느껴지는 부분 명확히 하기

### TODO
1. [ ] 가독성 - 주석, 함수명 등 정리
2. [ ] 재사용성, 유지보수의 관점에서 생각해보기 
3. [ ] 클린코드 가이드라인(레퍼런스) 맞춰서 코드 개선 부분 생각해보기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__5__`
