### ISSUE TITLE
[Client] 검색페이지 제품 북마크 사용성 개선

### ISSUE THREAD

**Issue by sarahsea** [codestates/Gunsigi#218]
### ISSUE
- Group:  `client`
- Type: `fix`
- Detail: 
호버 애니메이션으로 제품 북마크 선택이 어렵다는 다수의 피드백 -> 호버 효과도 적당히 주면서 북마크 사용감 개선하기
+추가 제품명이 길어서 생략부호(...)로 보이는 경우, 호버 시 전체 제품명 볼수 있게 하기 (or 미리보기 정보 주기) 

### TODO
1. [x] 다양한 호버 스타일 적용해보기
2. [x] ellipsis 비슷한 경우 검색
3. [x] 미리보기 레퍼런스 찾아보기
3. [x] 시안 몇개 적용해보고, 팀원 피드백 받기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__5__`
