### ISSUE TITLE
[ToDo] ToDo 리스트

### ISSUE THREAD

**Issue by Jin-suyeon** [codestates/Gunsigi#3]
## 1. 시스템 아키텍처

- [x]  JWT를 이용한 로그인 구현 | 필수 | ★
- [x]  OAuth 2.0을 이용한 소셜 로그인 | 권장 | ★
- [x]  인증 미들웨어 구현 | 필수 | ★
- [x]  각 필요한 라우터에 적용하기 | 필수 | ★

## 2. UI/UX

- [x]  회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 | 필수 | ★
- [x]  회원가입, 로그인 및 회원정보 수정 시 유효성 검사 | 필수  | ★
- [x]  소셜 로그인 외 서비스 자체 회원가입 기능 제공 | 필수 | ★
- [x]  회원가입 없이 '체험하기' 형식으로 가볍게 기능을 이용할 수 있는 장치 마련 - 비 회원이 제품 및 리뷰조회 가능 | 필수(Final only) || ★
- [x]  (소셜 로그인이 아닐 경우) 비밀번호 수정 기능 제공 | 필수 | ★
- [x]  리뷰삭제 | 필수 | ★
- [x]  랜딩페이지 리액트 슬릭 라이브러리 | 필수 | ★
- [x]  모바일/테블릿/ 데스크탑 반응형 디자인 | 필수 | ★
- [x]  검색을 위한 컴포넌트 개발 | 필수 | ★
- [x]  검색결과페이지 및 마이페이지에 북마크 기능 추가 | 필수 | ★
    - 마이페이지에 제품별 북마크탭
    - 마이페이지에 내가 쓴 리뷰 북마크탭
- [x]  어떤 제품을 찾는지 모르는 유저를 위한 카테고리 제공 | 필수 | ★
- [x]  제품 상세페이지 제공 | 필수 | ★
- [x]  로딩 인디케이터 구현 | 권장 | ★★
- [x]  리뷰작성(글, 사진첨부, 별점) | 권장 | ★★
- [x]  마이페이지를 통해 사용자 개인정보 수정 기능 제공 | 권장 | ★★
- [x]  회원가입 OAuth | 권장 | ★★
- [x]  무한 스크롤 | 도전 | ★★★
- [ ]  제품별 랭킹 | 도전 | ★★★
- [x]  검색페이지 판매수, 조회수, 추천수로 정렬 | 도전 | ★★★
- [ ]  리뷰 필터링(+ 유저의 성별, 나이정보를 추가로 받음), 리뷰 페이지네이션, 리뷰수정 | 도전 | ★★★
- [ ]  나에게 맞는 제품 찾기(유저에게 설문을 받아서 유저에게 맞는 제품을 추천) | 도전 | ★★★
- [ ]  검색창 연관검색어 자동완성기능 | 도전 | ★★★
- [x]  회원가입 시 이메일 인증 후 회원가입 완료 | 도전 | ★★★
- [ ]  반응형 4k | 도전 | ★★★
- [ ]  제품 구매 링크로 연결 | 신중 | ★★★★
- [ ]  건강기능식품 데이터의 첨가물 정보 API 이용 : 어떤 위험이 있는지 부작용 시각적 정보랑 함께 | 신중 | ★★★★
- [ ]  수익 창출의 관점으로 비지니스 모델 추가 | 신중 | ★★★★
- [ ]  관리자 페이지 | 신중 | ★★★★
- [ ]  고객센터 / FAQ | 신중 | ★★★★
- [ ]  잘못된 사진 발견시 신고가능 | 신중 | ★★★★
- [ ]  공지사항 / 게시판 | 신중 | ★★★★
- [ ]  다크모드 | 신중 | ★★★★
- [ ]  리뷰 댓글 | 신중 | ★★★★
- [x]  리뷰 정렬 (최신순, 인기순) + 리뷰도 좋아요가 존재 | 신중 | ★★★★

## 3. 스키마 및 API

- [x]  N:M (다대다) - 카테고리, 북마크, 리뷰 관계 설정 | 필수 | ★
- [x]  ERD (DB Diagram) 작성 | 필수 | ★
- [x]  API 작성 툴 (Postman, Gitbook API) 사용 | 필수 | ★
- [x]  ORM 사용 (sequelize) | 필수 | ★
- [x]  카테고리를 이용한 게시물 조회 API | 필수 | ★
- [x]  검색을 위한 스키마 조정 및 인덱싱 | 필수 | ★
- [x]  제품이미지 저장을 위한 S3생성 및 AWS SDK연동 | 필수 | ★
- [x]  북마크 기능 추가 | 필수 |★
    - 스키마 추가하기
    - API 구현하기
    - 제품 조회 API 수정하기 (북마크 등, 데이터 포함)
- [x]  OAuth 회원가입 기능 | 권장 | ★★
- [x]  사진업로드 | 도전 | ★★★
    - S3연동
- [x]  페이지네이션 구현 | 도전 | ★★★
- [x]  회원 이메일 인증 기능 | 신중 | ★★★★
- [x]  제품 인기순,리뷰순 정렬 추가 | 신중 | ★★★★
- [x]  리뷰 및 제품 정렬기능 | 신중 | ★★★★

## 4. DevOps

- [x]  도메인 구매 및 https 구축 | 필수 | ★
- [x]  [코드] precommit 단계에서 semistandard 적용 | 필수 |★
- [x]  [릴리즈] 깃허브 커밋메세지 규칙 합의 | 필수 | ★
- [x]  [코드] 버전 규칙 합의 | 필수 | ★
- [x]  [릴리즈] PR 형식 합의 | 필수 | ★
- [x]  [배포] AWS 구축 | 필수 | ★
- [x]  CI/CD Jenkins 구축 | 필수 | ★
- [x]  ESLint 컨벤션 통일 | 필수 |★
- [x]  초기 개발환경 구축 | 필수 | ★
- [x]  백엔드 테스트 코드 작성 | 권장 | ★★
