### ISSUE TITLE
[ Client ] 회원가입 모달 목업 디자인

### ISSUE THREAD

**Issue by junghoonme** [codestates/Gunsigi#34]
### ISSUE
- Group:  `client`
- Type: `design`
- Detail: 회원가입 모달 목업 디자인

### TODO
1. [ ] 모바일 반응형 목업 디자인
2. [ ] 태블릿 반응형 목업 디자인
3. [ ] 데스크탑 반응형 목업 디자인

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
