### ISSUE TITLE
[ Client ] 제품 상세 페이지 - 리뷰 작성 모달 목업 디자인

### ISSUE THREAD

**Issue by junghoonme** [codestates/Gunsigi#39]
### ISSUE
- Group:  `client`
- Type: `design`
- Detail: 제품 상세 페이지 - 리뷰 작성 모달 목업 디자인

### TODO
1. [x] 모바일 반응형 목업 디자인
2. [x] 태블릿 반응형 목업 디자인
3. [x] 데스크탑 반응형 목업 디자인

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
