### ISSUE TITLE
[NotToDo] Not ToDo 리스트

### ISSUE THREAD

**Issue by Jin-suyeon** [codestates/Gunsigi#4]
###

**코딩에 앞서...**

- [ ]  기획이 마무리되지 않은 상태에서 코딩을 시작함

###

**아키텍처**

- [ ]  논의되지 않은 새로운 스택 사용
- [ ]  핵심 기능이 외부 API에만 의존함 (api 사용량을 고려하지 않음)
- [ ]  인증/권한 사용시 passport.js를 사용함 (여러가지 이유로 권장하지 않습니다)

##

**사전 체크리스트 - 백엔드**

###

**API**

- [ ]  리소스 CRUD시 목적에 맞는 HTTP 메소드를 사용하지 않음
- [ ]  리소스 CRUD시 엔드포인트에 동사를 사용함
- [ ]  리소스 요청/응답시 필요한 json의 키/값 타입을 명시하지 않음
- [ ]  리소스 여러 개 조회 시 배열을 사용하지 않음
- [ ]  HTTP 응답 코드의 사용이 적절하지 않음
- [ ]  응답 에러 메시지의 일관성이 없음
- [ ]  리소스 조회 시 json과 스키마 field간의 일관성이 없음
- [ ]  리소스 생성 시 신규 아이디를 리턴하지 않음
- [ ]  사용자 정보를 필요로 하는 요청에 토큰 또는 세션을 사용하지 않음
- [ ]  특정 사용자와 연관된 리소스 조회시 권한 문제를 고려하지 않음
- [ ]  JWT 사용시 헤더에 토큰을 전달하는 내용을 명시하지 않음
- [ ]  엔드포인트가 spinal-case (소문자와 대시 문자열) 를 따르지 않음
- [ ]  GET 요청에서 쿼리 파라미터 대신 HTTP body를 사용함
- [ ]  HTTP body를 사용해야 하는 상황에서 쿼리 파라미터를 사용함

###

**스키마**

- [ ]  스키마의 1:N, N:M 관계가 적절하지 않음
- [ ]  조인 테이블의 이름이, 관계있는 테이블 이름을 포함하지 않음
- [ ]  리소스의 CRUD에 필요한 테이블이 존재하지 않음

##

**사전 체크리스트 - 프론트엔드**

- [ ]  이미 전부 디자인 가이드가 만들어져있는 CSS 프레임워크를 사용함 (ex. Material UI, Ant design, bootstrap 등)

##

**사후 체크리스트 - 프론트엔드**

- [ ]  UX상 나쁜 디자인으로 평가받는 브라우저 내장 기능(alert, prompt, confirm)의 지나친 사용
- [ ]  콘텐츠가 존재하나 스크롤할 수 없는 영역이 존재함
- [ ]  "스크롤바 항상보기" 옵션을 사용시, 불필요하게 스크롤바가 보임
- [ ]  데이터가 0개일 때, 아무런 안내가 없어 버그처럼 보임
- [ ]  로딩 실패 시 적절한 피드백을 제공하지 않음
- [ ]  로딩 시 레이아웃이 깨짐
- [ ]  로딩 처리를 전혀 하지 않음
- [ ]  개발자 콘솔을 열었을 때 자바스크립트 에러가 발생함
- [ ]  로그인을 하지 않을 경우 아무런 기능도 사용할 수 없음
