### ISSUE TITLE
[ Client ] 로딩 인디케이터 추가

### ISSUE THREAD

**Issue by sarahsea** [codestates/Gunsigi#86]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 건식이 로딩 인디케이터 구현

### TODO
- [x] 필요한 svg, png 파일 만들기
- [x] 물 차오르는 애니메이션의 로딩 인디케이터
- [x] 튀어 오르는 알약의 애니메이션의 로딩 인디케이터

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
